export const images = [
  { url: "/gallary/gal1.jpg", cat: "Fineline" },
  { url: "/gallary/gal2.jpg", cat: "Mandala" },
  { url: "/gallary/gal3.jpg", cat: "Lettering" },
  { url: "/gallary/gal4.jpg", cat: "Floral" },
  { url: "/gallary/gal5.jpg", cat: "Dotwork" },
  { url: "/gallary/gal6.jpg", cat: "Traditional" },
  { url: "/gallary/gal7.jpg", cat: "Mandala" },
  { url: "/gallary/gal8.jpg", cat: "Floral" },
  { url: "/gallary/gal9.jpg", cat: "Traditional" },
  { url: "/gallary/gal10.jpg", cat: "Lettering" },
  { url: "/gallary/gal11.jpg", cat: "Floral" },
  { url: "/gallary/gal12.jpg", cat: "Dotwork" },
  { url: "/gallary/gal13.jpg", cat: "Dotwork" },
  { url: "/gallary/gal14.jpg", cat: "Fineline" },
  { url: "/gallary/gal15.jpg", cat: "Traditional" },
  { url: "/gallary/gal16.jpg", cat: "Fineline" },
  { url: "/gallary/gal17.jpg", cat: "Mandala" },
];
